### ISSUE TITLE
Currency GBP

### ISSUE THREAD

**Issue by JeffPaulett** [hintofbasil/Hodl#17]
Could we have United Kingdom GBP as a currency on the app please.

**Comment by hintofbasil** [comment]
Hi Jeff,

GBP should be listed in the app already.  It is listed as "British Pound (GBP)" in the settings page.  It is right below Euro.

Please can you re-fresh the application data (by swiping down on the main page) and then check if it is still missing.  If it is I will take a further look when I get an opportunity.

**Comment by hintofbasil** [comment]
Closing this issue as there was no response.
