### ISSUE TITLE
CoinMarketCap API deprication

### ISSUE THREAD

**Issue by hintofbasil** [hintofbasil/Hodl#21]
CoinMarketCap has released a new version of their API.  They are deprecating the old one on December 4th.

This new API has strict limits and the results may need to be cached.

API details at https://coinmarketcap.com/api/

**Comment by hintofbasil** [comment]
Fixed in c49b8b02d04d51a709a00593f7870db094c5ae31

**Comment by tmlee** [comment]
Alternatively you can consider our public open API at https://www.coingecko.com/api
Happy to answer any questions or concerns you may have
